import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#4c4735",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-background": "#111d23",
        "surface-dim": "#cfdce4",
        "on-tertiary-container": "#ff6559",
        "on-primary-container": "#8690ee",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#cfc6b0",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#e0e0ff",
        "on-secondary-fixed": "#1f1b0d",
        "surface-container-highest": "#d7e4ec",
        "surface": "#f4faff",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary-fixed": "#410002",
        "surface-container": "#e3f0f8",
        "secondary-container": "#e8dfc8",
        "inverse-surface": "#263238",
        "on-surface-variant": "#454652",
        "on-surface": "#111d23",
        "on-tertiary-fixed-variant": "#93000b",
        "tertiary-container": "#680005",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb4ab",
        "secondary-fixed": "#ebe2cb",
        "inverse-primary": "#bdc2ff",
        "on-secondary-container": "#686250",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#bdc2ff",
        "surface-variant": "#d7e4ec",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#000767",
        "tertiary": "#400002",
        "surface-bright": "#f4faff",
        "primary": "#000666",
        "background": "#f4faff",
        "surface-container-low": "#e9f6fd",
        "primary-container": "#1a237e",
        "outline": "#767683",
        "surface-tint": "#4c56af",
        "surface-container-high": "#ddeaf2",
        "on-primary-fixed-variant": "#343d96",
        "inverse-on-surface": "#e6f3fb",
        "secondary": "#645e4c",
        "outline-variant": "#c6c5d4",
        "natural-beige": "#E1D8C1",
        "deep-indigo": "#1A237E",
        "warm-ivory": "#F9F7F2",
        "textile-red": "#B71C1C",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "gutter": "16px",
        "table-row-height": "40px",
        "unit": "4px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
